### PR TITLE
Dialog GUI rework

### PR DESCRIPTION
**Pull request by TyKonKet**
Now they are a bit beautier to see and some user interaction bugs have been fixed (eg. GUI closing after clicking out of text box)

### CODE REVIEW

**Comment by raxtor** [comment]
Nice.. is this one solving also problem with cursor focus? Actually there is needed always click to input before writting.

**Comment by TyKonKet** [comment]
Not sure let me check 😄

**Comment by TyKonKet** [comment]
Ok, in the create folder dialog it doesn't work and in the target and driver dialogs it works only the first time.
Let me some time, I'll try to fix it.

**Comment by Stephan-S** [comment]
great work @TyKonKet 
Would you like me to wait before merging it?

**Comment by Stephan-S** [comment]
Wow, that was quick! Nice work!

**Comment by TyKonKet** [comment]
> great work @TyKonKet
> Would you like me to wait before merging it?

Yes please, now the focus works, but only the first time after the gui instance (game load) and I want to fix that.

**Comment by TyKonKet** [comment]
@Stephan-S , maybe I understood why we have to delay the opening of dialogs to prevent glitches.
How do you handle the mouse inputs for the HUD?
Commonly the mouse click is defined as the sequence of two lower level events ( mouse button down & mouse button up)
So we should abstract all with 3 events:
1) Mouse button down on a HUD element
2) Mouse button up on a HUD element
3) Mouse click on a HUD element (only if previous events have been on the same element)

If you are just listening at the mouse down event, here is the problem because the following mouse up event triggers on the dialog/GUI and cause the loss of focus and even the 'onEnterPressed' event.
To be honest, in that case, even the delayed opening  of the GUI doesen't really solve the problem at all, because if the delta time between 'down' and 'up' is larger then the opening delay, the mouse button up event triggers again on the GUI.

**Pull request merged**
