### PR TITLE
register.lua refactoring

### PR DESCRIPTION
**Pull request by TyKonKet**
It's not that long since I started using this mod intensely, but I'm really enjoying it.
This is why I would really like to help you improve it, but to be able to do it, I need to get a little more familiar with the code base.
So I thought, what could be better than starting with a simple refactoring?
The script works exactly like before, but now it's a bit more GIANTS style, or at least how they would like the specilization to work and (in my opinion) easier to read and understand.
If you don't want to merge my changes and keep your script, I understand it and it won't be a problem.

### CODE REVIEW

**Comment by TyKonKet** [comment]
Obviously I have already tested it and checked that the spec is registered correctly on all vehicle types.

**Comment by DeckerMMIV** [comment]
There is even no need to load the modDesc.xml file, just to get the version value.

I use this in my mods (global scope): `g_modManager:getModByName(g_currentModName).version`

**Comment by TyKonKet** [comment]
Is it really useful another duplicate of the version in the **AutoDrive.lua** script?
Line 2 : `AutoDrive.Version = "1.0.6.6";`

**Comment by Stephan-S** [comment]
@TyKonKet Thank you for your contribution.
I am really looking forward to finally having someone 'join the team' :-)
Welcome aboard!



> Is it really useful another duplicate of the version in the **AutoDrive.lua** script?
> Line 2 : `AutoDrive.Version = "1.0.6.6";`

Quite honestly. This was just for convenience because I was too lazy to ever check where I could get that information from without any hussle.

**Pull request merged**
