### PR TITLE
New load mode

### PR DESCRIPTION
**Pull request by jala15**
Added a load mode based on pickup and deliver mode to refill seeders and fertilizers in combination with courseplay. Unloading point is now loading point for this mode. Made in a new file and removed the restriction of being dischargeable.

### CODE REVIEW

**Comment by Stephan-S** [comment]
Hey
that has to be the largest pull request anyone has ever done :-)
You really went through a lot of the code to get this up and running. Great work.

Have you already tested it? I will try to test this at the weekend before merging it to the main branch.
Thank you very much for your contribution!

Best regards,
Stephan

**Comment by jala15** [comment]
Hi
Thank you very much. A lot of my code is based on yours, you did the hard job :) 
I modified the mod for myself a week ago, based on version 1.0.3.1 and have been using it working with no bugs. Today I had a bit of spare time and wanted to share it so created a github acount, made the changes you have made to get it up to date and sent the pull request.
I'm testing it now and seems to work fine again after fixing a bug. I'm new at github so I might not know how to make some things but I think the bugfix is pull requested now. I'm not sure about covers closing after refilling. Please take a further look at this part.
Thank you very much for your time and for making such a great mod

**Comment by Roby1164** [comment]
Hi jale15, tell me how it works, your modification, to load the seeder, etc. .. ??? Could it also work with the manure and sewage spreader ???

**Comment by jala15** [comment]
I have only tested with calk/lime spreader as it gets empty quickly, but it should work with every fillable atachment. I will try it and confirm.
To make it work, in combination with courseplay, you set the upper destination to the field you are working, and the lower destination (the unloading one in pick up and deliver) to the loading silo were you have your seeds, lime, manure, fertilizer or liquid manure stored. You have to choose the fruit to be loaded from the autodrive HUD as for pick up and deliver mode. 
When the atachment is empty, courseplay (if the option to call autodrive is on) calls autodrive, it drives to the loading silo, gets full and comes back to the field to finish the job :)

**Comment by Roby1164** [comment]
Opss, I skipped the fact that you use it in combination with the courseplay, so it can't work in MP, since the CP just doesn't work in CP, I realized that it worked alone, that is using a separate trailer, of the seed charge type or fertilizer, the one with the tube, to fill the spill lime when it stops, because it is empty ..
I'll try it in SP, to better understand how it works ...
So to summarize, you use the CP, to do the work of spreading lime in the field, and in combination set the AD to make it go to load, when it's empty ... Thanks

**Comment by jala15** [comment]
@Roby1164 I use it in combination with courseplay because it becomes more useful this way. You can use it without CP anyway, for example to get your fertilizer loaded and driven to a field. 

Here I leave a video showing how to set up and how it works: https://youtu.be/vEO4pEvz9kA

**Pull request merged**
