### PR TITLE
Cleaned speedmeter icon

### PR DESCRIPTION
**Pull request by raxtor**
cleaned speedmeter icon
button_base

### CODE REVIEW

**Comment by raxtor** [comment]
Here is transparent PNG... I noticed u changet somehow icon background color.. so change it as you need
speedmeter

**Comment by Stephan-S** [comment]
thanks @raxtor !
Can you also create the transparent one with the border around it?
Take the border from an already existing transparent one please, since it will differ from the old one with no transparancy

**Comment by raxtor** [comment]
U can merge my DDS, I tested it and all seems ok. *.zip added for sure
[speedmeter.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3800323/speedmeter.zip)

**Comment by raxtor** [comment]
Well, I changed it a little.. it looks better..
button_base
[speedmeter.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3800557/speedmeter.zip)

**Comment by Stephan-S** [comment]
Thank you. I manually included the file in my last commit!

**Pull request closed without merging**
