### PR TITLE
FIX height calculation when moving waypoints

### PR DESCRIPTION
**Pull request by Exceptionfault**
Hi guys,

while testing my smooth curves feature, I hit the problem that my waypoints sunk into the ground.  Basically the same happened with "normal" AD waypoints when moving them manually, for example at the T-shape in Felsbrunn right in front of the farm.

beforeRaycast

Doing some research, I found a hint, that the widely used `getTerrainHeightAtWorldPos` returns the height of the terrain which is not the same as the height of a road. On some maps there are gaps under the road which leads to the described problem.
By exchanging the function with a raycast I got a much better and more accurate result. 

withRaycast

So technically, the new method might be a bit slower but should give much better results.
Personally, for me the only reason to change the drawing height above the vehicle was to work around waypoints that sunk underneath the road...

I commented out lot of the `moveNodeToMousePos` function, because replacing all this with just one line looks way to easy and maybe I missed something ? :-)

### CODE REVIEW

**Comment by Exceptionfault** [comment]
I've "fixed" the creation of new waypoints via Ctrl+LMB as well. This time I've removed a bunch of code which maybe I didn't understand it's purpose or it's just no longer necessary. With the raycast, I can't see any more problems with waypoints sinking in the ground. But as already mentioned above - please tell me if I miss something and that code that I commented/removed was very important in some case...

**Comment by TyKonKet** [comment]
@Exceptionfault at the moment I haven't yet had the opportunity to test it, but I can think of a possible problem:
What happens if you move or create a waypoint that's under a tractor or tool?
The raycast would probably hit the tractor collision? If so, will the y-position of the waypoint be incorrect?
Could you please take a test?
One possible solution could be to raycast with a collision mask that ignores vehicles.

**Comment by Exceptionfault** [comment]
@TyKonKet you're absolutely right - the waypoint jumps on top of a tractor and even on top of a street sign. I've found the hint for the raycast here https://gdn.giants-software.com/thread.php?categoryId=3&threadId=8381 and they have used a collision mask of `59`.
To be honest - no idea what that is...  I've found some numbers in the `ADCollSensor` but I'm not yet sure what would be the right mask here...

**Comment by TyKonKet** [comment]
Mhh, that's a problem I don't know collision masks too :D
Let me do some searching...

**Comment by TyKonKet** [comment]
Ok you can try with `15`
Following what we can see on [ADCollSensor](https://github.com/Stephan-S/FS19_AutoDrive/blob/master/FS19_AutoDrive/scripts/Sensors/CollSensor.lua)
```lua
ADCollSensor.mask_Non_Pushable_1 = 1
ADCollSensor.mask_Non_Pushable_2 = 2
ADCollSensor.mask_static_world_1 = 3
ADCollSensor.mask_static_world_2 = 4
ADCollSensor.mask_tractors = 6
ADCollSensor.mask_combines = 7
ADCollSensor.mask_trailers = 8
ADCollSensor.mask_dynamic_objects = 12
ADCollSensor.mask_dynamic_objects_machines = 13
ADCollSensor.mask_trigger_player = 20
ADCollSensor.mask_trigger_tractor = 21
ADCollSensor.mask_trigger_combines = 22
ADCollSensor.mask_trigger_fillables = 23
ADCollSensor.mask_trigger_dynamic_objects = 24
ADCollSensor.mask_trigger_trafficVehicles = 25
ADCollSensor.mask_trigger_cutters = 26
ADCollSensor.mask_kinematic_objects_wo_coll = 30
```
It should collide/hit only with static objects

**Comment by Exceptionfault** [comment]
Yeah, helped a little bit - but still not perfect. The raycast no longer hits the tractor but it hits the tires and attached weights. Maybe I need to switch from `getFirstHit`to `getAllHits`and figure out which `y` value to use based on returned object types.
Also I've noticed that I've messed up the creation of waypoints when looking from different angles - maybe that huge amount of code with project() and unproject() had some sense :) 

Definitely keep this PR open and let me do some more work on this...

**Comment by Exceptionfault** [comment]
Ok, I finally solved it - even a collision mask of `12` is enough. The reason why it initially still hit parts of the tractor was the original code of AD, that means the current version has that problem too. 
So I replaced the current code of moving waypoints with just the new height calculation and it works very well IMO. I even tested on several triggers, ramps and even on "higher" bridges crossing ditches like on NFMarsch.
I kept most of the part for waypoint creation as it is responsible for getting the right depth. I just changed the final part that gets the hight. Works pretty well IMO, too.

And now the bad part :-) I messed with my branches for testing and did a merge instead of a cherry pick - so my source branch now also contains parts of the smooth curve connection feature. I'm trying to fix this later... if not I will close this PR and create a new one with a clean branch - sorry for that.. so please still don't merge

**Comment by Exceptionfault** [comment]
Done - i've cleaned up the branch. I'd say - **this is ready for testing ** :)

**Pull request merged**
