### PR TITLE
Update translation_ru.xml

### PR DESCRIPTION
**Pull request by Gonimy-Vetrom**

### CODE REVIEW

**Comment by Anonymous-any** [comment]
Hi @Gonimy-Vetrom I need you help if you can...and have the time.
I see you repository is clean and look updated, only one push patch-1 like this one and all and all :)
I would like to know how do you proceed for all your steps please because I don't really understand all on Github. My cloned repository look for me a real disaster for me and is not good updated. Like if I want to update the repo from @Stephan-S Github say my it can't do this if I not use a new branch my brain is in short and other thing where I make long time to do.
Br

**Comment by Gonimy-Vetrom** [comment]
Screenshot_4
@Anonymous-any. I always try to wait until the owner of the repository approves my change in the file, and then I make a new request (if necessary). I rarely edit a branch that has already been created, because, too, I cannot understand what the consequences would be.

**Comment by Anonymous-any** [comment]
@Gonimy-Vetrom thank for reply Yes I do like you do it too, but I think there something more you do because my repository don't update itself like your below (arrows):

Do you mean I have to wait few days before it updating itself that it ?

**Comment by Gonimy-Vetrom** [comment]
@Anonymous-any Not. GitHub itself will not do anything. I meant that the author himself unites and the branch closes itself.
Screenshot_3

**Comment by Anonymous-any** [comment]
@Gonimy-Vetrom Hep :) Thank yes that it's ok but I don't understand like yours why to mine I've not all cloned like the 3 releases versions as example you know. When I add a change it only import the file I modifying to a branch it create itself for pull request it's ok and look normal like yours and fortunately I want to say, but your repository look all updated ! not only your pull translation. This is this step who I not make it good to my side viewing the result...and I would like to learn how you do it. Regard

**Comment by Anonymous-any** [comment]
Ok it seem I found why you have:
`master Updated 3 days ago by Stephan Schlosser`

**Pull request merged**
