### PR TITLE
Updated AD Editor to v1.1.1.4 featues

### PR DESCRIPTION
**Pull request by KillBait**
Changes

- Updated XML loading and saving to include the flag tag, now saves any subPrio routes properly
- Note: configs without the flag tag in XML get assigned a temp one internally so not to cause issues in editor. they are not saved back to the XML on saving)
- Added warning about older config versions without the flag tag not supporting the new 1.1.1.4 features, requiring an AD update and ingame load and save.
- Added flag support to mapNodes to display the new subPrio routes
- Added GUI buttons to change route priority and add subPrio nodes directly if config file supports them
- Adjusted route colours to match ingame editor

### CODE REVIEW

**Comment by Williwillswisse** [comment]
Hi KillBait,
can't get it going. Do you have some hints for me ?

**Comment by KillBait** [comment]
How exactly is it not working?.. did it compile correctly?

**Comment by Williwillswisse** [comment]
Compile ?? 🙈
What do I have to do ?
I'am absolute knowledge free concerning Java ...

**Comment by KillBait** [comment]
this was an update to the sourcecode of AD, you will have to wait for the next release of AutoDrive to get the updated runtime

**Comment by Williwillswisse** [comment]
I think this is an update of the external java editor ? It's an extra part of AD. The guy who took care of it is no longer available for our team.

**Comment by KillBait** [comment]
correct.. its an update to external the java editor, i have basic java knowledge, so its not exactly a complex update, just one that's within my java skill level

**Comment by Williwillswisse** [comment]
I have downloaded your your zip and started the AD.jar. Can't see something new. What do I have to do to get the new feature working ? Can you build a version running out of the box ?

**Comment by KillBait** [comment]
you can download (or clone) the repository and import it an IDE of your choice and compile the new version yourself (or wait for an updated version of AutoDrive to release).

I can supply you the updated JAR file, but i wont attach it here unless it's O.K with the AD devs

**Comment by Stephan-S** [comment]
Feel free to include the updated jar in your PR here :-)
Thank you for your contribution!

**Comment by KillBait** [comment]
> Feel free to include the updated jar in your PR here :-)
> Thank you for your contribution!

My pleasure, i use AD a lot so it's my small way to say thankyou :-)

BTW... you may want to adjust the version number string of the editor to what you see fit.. i just changed it to a random one.

Here is a link to the new JAR file[https://drive.google.com/file/d/1VYLmle_xVzGLu_gxzfacMU-tPiSr0g3E/view?usp=sharing](/url)

**Comment by Williwillswisse** [comment]
Thanks a lot KillBait ... looks really good.

**Pull request merged**
